### ISSUE TITLE
devtools are required: Is that neccessary?

### ISSUE THREAD

**Issue by hella-schu** [medialta/contao-material#12]
I'm used to turn off unused extensions / parts of contao like faq or also devtools. If I turn devtools to inactive, the contao installation is broken.
Maybee you could remove devtools as a dependency?

**Comment by sebj54** [comment]
This is actually necessary because we rewrote a devtools template. Anyway, it shouldn't break your installation.
We are looking for a non-blocking solution for next release.

**Comment by hella-schu** [comment]
Thank you!
